### ISSUE TITLE
Cargo has dynamic loading (and doesn't work properly)

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE_MISSIONS#2]
None of the cargo test missions work, there's a bit of dynamic loading in the moose of them, also if you replace the moose with mooose static, some at least are still broken, like transferring, the guys go in, then they get out, then they walk to the next place and then get in.
38898.623 INFO    SCRIPTING: *** MOOSE DYNAMIC INCLUDE START ***
38898.623 INFO    SCRIPTING: Moose Generation Timestamp: 20170401_1103
38898.623 ERROR   DCS: Mission script error: : [string "e:\temp\DCS\/~mis000011DE"]:11: can't open 'Scripts/Moose/Utilities/Routines.lua'
stack traceback:
    [C]: ?
    [C]: in function 'assert'
    [string "e:\temp\DCS\/~mis000011DE"]:11: in function 'Include'
    [string "e:\temp\DCS\/~mis000011DE"]:24: in main chunk

**Comment by FlightControl-Master** [comment]
From which branch are you loading these?

**Comment by FlightControl-Master** [comment]
@Grey-Echo ypu see... Default branch is not master-release...
